# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IL3yYBM2uY-EAeXRTHQzShwaORzTlvod
"""

pip install PyTDC

from tdc.single_pred import ADME
import pandas as pd

dataset =  ADME(name="Solubility_AqSolDB")

dataset.label_distribution()

split = dataset.get_split (method = "scaffold")

split["train"].head()

from rdkit import Chem
from rdkit.Chem import Descriptors

mol = Chem.MolFromSmiles('CC(=O)Oc1ccccc1C(=O)O')  # Example: Aspirin

features = {
    "MolWt": Descriptors.MolWt(mol),
    "LogP": Descriptors.MolLogP(mol),
    "TPSA": Descriptors.TPSA(mol),
    "HBD": Descriptors.NumHDonors(mol),
    "HBA": Descriptors.NumHAcceptors(mol),
    "RotatableBonds": Descriptors.NumRotatableBonds(mol),
    "AromaticRings": Descriptors.NumAromaticRings(mol),
    "MR": Descriptors.MolMR(mol),
    "Fsp3": Descriptors.FractionCSP3(mol),
    "FormalCharge": Chem.GetFormalCharge(mol)
}

features

